{
 "title": "Opera",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Churn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inter Arrival Time Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(simulator_churn_inter_arrival_bucket{job=\"opera\"}[2m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(simulator_churn_inter_arrival_bucket{job=\"opera\"}[2m])) by (le))",
     "legendFormat": "70th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(simulator_churn_inter_arrival_bucket{job=\"opera\"}[2m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Session Length Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(simulator_churn_session_length_bucket{job=\"opera\"}[2m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(simulator_churn_session_length_bucket{job=\"opera\"}[2m])) by (le))",
     "legendFormat": "70th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(simulator_churn_session_length_bucket{job=\"opera\"}[2m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Offline Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "simulator_churn_offline_nodes{job=\"opera\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "simulator_churn_online_nodes{job=\"opera\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inter-arrival Time Distribution",
   "type": "histogram",
   "description": "x-axis is the buckets of inter-arrival times in seconds\ny-axis is the counter of inter-arrival points in each bucket",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(simulator_churn_inter_arrival_bucket{job=\"opera\"}[2m])) / sum(rate(simulator_churn_inter_arrival_count{job=\"opera\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Session Length Distribution",
   "type": "histogram",
   "description": "x-axis is the buckets of session length times in seconds\ny-axis is the counter of session length points in each bucket",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(simulator_churn_session_length_bucket{job=\"opera\"}[2m])) / sum(rate(simulator_churn_session_length_count{job=\"opera\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average Received Messages (Per Node)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg by (job) (rate(network_network_message_received_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Sent Messages (Per Node)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "avg by (job)(rate(network_network_message_sent_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}