{
 "title": "OperaNetworking",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Churn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inter Arrival Time (ms)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "simulator_churn_inter_arrival_bucket{job=\"opera\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Middleware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Average Received Messages (Per Node)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg by (job) (rate(network_middleware_message_received_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Sent Messages (Per Node)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "avg by (job)(rate(network_middleware_message_sent_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}