{
 "title": "OperaNetworking",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Churn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inter Arrival Time Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(simulator_churn_inter_arrival_bucket{job=\"opera\"}[2m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(simulator_churn_inter_arrival_bucket{job=\"opera\"}[2m])) by (le))",
     "legendFormat": "70th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(simulator_churn_inter_arrival_bucket{job=\"opera\"}[2m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Session Length Percentile (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(simulator_churn_session_length_bucket{job=\"opera\"}[2m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(simulator_churn_session_length_bucket{job=\"opera\"}[2m])) by (le))",
     "legendFormat": "70th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(simulator_churn_session_length_bucket{job=\"opera\"}[2m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Average Received Messages (Per Node)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg by (job) (rate(network_network_message_received_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Sent Messages (Per Node)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "avg by (job)(rate(network_network_message_sent_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}