package modules.logger;

import node.Identifier;
import org.slf4j.LoggerFactory;

/**
 * Encapsulates logger for opera project.
 */
public class OperaLogger {
  /**
   * Logger prefix that is used to filter out logs generated by this project.
   */
  private static final String LOGGER_NAME = "io.github.yhassanzadeh13";

  /**
   * Creates a logger for the given class name prefixed by the logger name.
   *
   * @param className class name for which a logger is created.
   * @return logger for the class.
   */
  public static Logger getLoggerForNodeComponent(String className, Identifier nodeId, String component) {
    Logger logger = new Logger(LoggerFactory.getLogger(LOGGER_NAME + "." + className));
    logger.addPrefix("node_id: " + nodeId.toString());
    logger.addPrefix("component: " + component);
    return logger;
  }

  /**
   * Creates a logger for the given class name prefixed by the logger name.
   *
   * @param className class name for which a logger is created.
   * @return logger for the class.
   */
  public static Logger getLoggerForSimulator(String className) {
    Logger logger = new Logger(LoggerFactory.getLogger(LOGGER_NAME + "." + className));
    logger.addPrefix("simulator-");
    return logger;
  }
}